// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.
// @dart = 2.12

import 'dart:core';
import 'package:flutter_mirror/model/Person.dart' as prefix1;
import 'package:flutter_mirror/utils/Reflect.dart' as prefix0;

// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: implementation_imports

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.MyReflectable(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'Person',
            r'.Person',
            7,
            0,
            const prefix0.MyReflectable(),
            const <int>[0, 1, 2, 3, 7, 8],
            const <int>[9, 10, 11, 12, 13, 3, 4, 5, 6],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (bool b) => ({firstName, lastName, info}) => b
                  ? prefix1.Person(
                      firstName: firstName, info: info, lastName: lastName)
                  : null,
              r'fromJson': (bool b) =>
                  (json) => b ? prefix1.Person.fromJson(json) : null
            },
            0,
            0,
            const <int>[],
            null,
            null)
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(r'firstName', 33797, 0,
            const prefix0.MyReflectable(), -1, -1, -1, null, null),
        r.VariableMirrorImpl(r'lastName', 33797, 0,
            const prefix0.MyReflectable(), -1, -1, -1, null, null),
        r.VariableMirrorImpl(r'info', 2130949, 0, const prefix0.MyReflectable(),
            -1, -1, -1, null, null),
        r.MethodMirrorImpl(r'toJson', 4325378, 0, -1, -1, -1, null,
            const <int>[], const prefix0.MyReflectable(), null),
        r.ImplicitGetterMirrorImpl(const prefix0.MyReflectable(), 0, 4),
        r.ImplicitGetterMirrorImpl(const prefix0.MyReflectable(), 1, 5),
        r.ImplicitGetterMirrorImpl(const prefix0.MyReflectable(), 2, 6),
        r.MethodMirrorImpl(r'', 0, 0, -1, -1, -1, null, const <int>[0, 1, 2],
            const prefix0.MyReflectable(), null),
        r.MethodMirrorImpl(r'fromJson', 1, 0, -1, -1, -1, null, const <int>[3],
            const prefix0.MyReflectable(), null),
        r.MethodMirrorImpl(r'==', 131074, -1, -1, -1, -1, null, const <int>[4],
            const prefix0.MyReflectable(), null),
        r.MethodMirrorImpl(r'toString', 131074, -1, -1, -1, -1, null,
            const <int>[], const prefix0.MyReflectable(), null),
        r.MethodMirrorImpl(r'noSuchMethod', 65538, -1, -1, -1, -1, null,
            const <int>[5], const prefix0.MyReflectable(), null),
        r.MethodMirrorImpl(r'hashCode', 131075, -1, -1, -1, -1, null,
            const <int>[], const prefix0.MyReflectable(), null),
        r.MethodMirrorImpl(r'runtimeType', 131075, -1, -1, -1, -1, null,
            const <int>[], const prefix0.MyReflectable(), null)
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(
            r'firstName',
            41990,
            7,
            const prefix0.MyReflectable(),
            -1,
            -1,
            -1,
            null,
            null,
            null,
            #firstName),
        r.ParameterMirrorImpl(
            r'lastName',
            41990,
            7,
            const prefix0.MyReflectable(),
            -1,
            -1,
            -1,
            null,
            null,
            null,
            #lastName),
        r.ParameterMirrorImpl(r'info', 2139142, 7,
            const prefix0.MyReflectable(), -1, -1, -1, null, null, null, #info),
        r.ParameterMirrorImpl(r'json', 2129926, 8,
            const prefix0.MyReflectable(), -1, -1, -1, null, null, null, null),
        r.ParameterMirrorImpl(r'other', 32774, 9, const prefix0.MyReflectable(),
            -1, -1, -1, null, null, null, null),
        r.ParameterMirrorImpl(r'invocation', 32774, 11,
            const prefix0.MyReflectable(), -1, -1, -1, null, null, null, null)
      ],
      <Type>[prefix1.Person],
      1,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'toJson': (dynamic instance) => instance.toJson,
        r'firstName': (dynamic instance) => instance.firstName,
        r'lastName': (dynamic instance) => instance.lastName,
        r'info': (dynamic instance) => instance.info
      },
      {},
      <m.LibraryMirror>[
        r.LibraryMirrorImpl(r'', Uri.parse(r'reflectable://0/'),
            const prefix0.MyReflectable(), const <int>[], {}, {}, null, null)
      ],
      []),
  const prefix1.MetaReflector(): r.ReflectorData(
      <m.TypeMirror>[], null, null, <Type>[], 0, {}, {}, null, [])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
