// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.
// @dart = 2.12

import 'dart:core';
import 'package:flutter_mirror/model/common/Result.dart' as prefix1;
import 'package:flutter_mirror/model/dto/CounterDTO.dart' as prefix2;
import 'package:flutter_mirror/utils/Reflect.dart' as prefix0;

// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: implementation_imports

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.MyReflectable(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'Result',
            r'.Result',
            7,
            0,
            const prefix0.MyReflectable(),
            const <int>[0, 1, 2, 4, 8, 9],
            const <int>[10, 11, 12, 13, 14, 4, 5, 6, 7],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (bool b) => ({code, message, data}) => b
                  ? prefix1.Result(code: code, data: data, message: message)
                  : null,
              r'fromJson': (bool b) =>
                  (json) => b ? prefix1.Result.fromJson(json) : null
            },
            0,
            0,
            const <int>[],
            null,
            null),
        r.NonGenericClassMirrorImpl(
            r'CounterDTO',
            r'.CounterDTO',
            7,
            1,
            const prefix0.MyReflectable(),
            const <int>[3, 15, 17, 18],
            const <int>[10, 11, 12, 13, 14, 15, 16],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (bool b) =>
                  ({count}) => b ? prefix2.CounterDTO(count: count) : null,
              r'fromJson': (bool b) =>
                  (json) => b ? prefix2.CounterDTO.fromJson(json) : null
            },
            1,
            1,
            const <int>[],
            null,
            null)
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(r'code', 33797, 0, const prefix0.MyReflectable(),
            -1, -1, -1, null, null),
        r.VariableMirrorImpl(r'message', 33797, 0,
            const prefix0.MyReflectable(), -1, -1, -1, null, null),
        r.VariableMirrorImpl(r'data', 17413, 0, const prefix0.MyReflectable(),
            -1, -1, -1, null, null),
        r.VariableMirrorImpl(r'count', 33797, 1, const prefix0.MyReflectable(),
            -1, -1, -1, null, null),
        r.MethodMirrorImpl(r'toJson', 4325378, 0, -1, -1, -1, null,
            const <int>[], const prefix0.MyReflectable(), null),
        r.ImplicitGetterMirrorImpl(const prefix0.MyReflectable(), 0, 5),
        r.ImplicitGetterMirrorImpl(const prefix0.MyReflectable(), 1, 6),
        r.ImplicitGetterMirrorImpl(const prefix0.MyReflectable(), 2, 7),
        r.MethodMirrorImpl(r'', 0, 0, -1, -1, -1, null, const <int>[0, 1, 2],
            const prefix0.MyReflectable(), null),
        r.MethodMirrorImpl(r'fromJson', 1, 0, -1, -1, -1, null, const <int>[3],
            const prefix0.MyReflectable(), null),
        r.MethodMirrorImpl(r'==', 131074, -1, -1, -1, -1, null, const <int>[4],
            const prefix0.MyReflectable(), null),
        r.MethodMirrorImpl(r'toString', 131074, -1, -1, -1, -1, null,
            const <int>[], const prefix0.MyReflectable(), null),
        r.MethodMirrorImpl(r'noSuchMethod', 65538, -1, -1, -1, -1, null,
            const <int>[5], const prefix0.MyReflectable(), null),
        r.MethodMirrorImpl(r'hashCode', 131075, -1, -1, -1, -1, null,
            const <int>[], const prefix0.MyReflectable(), null),
        r.MethodMirrorImpl(r'runtimeType', 131075, -1, -1, -1, -1, null,
            const <int>[], const prefix0.MyReflectable(), null),
        r.MethodMirrorImpl(r'toJson', 4325378, 1, -1, -1, -1, null,
            const <int>[], const prefix0.MyReflectable(), null),
        r.ImplicitGetterMirrorImpl(const prefix0.MyReflectable(), 3, 16),
        r.MethodMirrorImpl(r'', 0, 1, -1, -1, -1, null, const <int>[6],
            const prefix0.MyReflectable(), null),
        r.MethodMirrorImpl(r'fromJson', 1, 1, -1, -1, -1, null, const <int>[7],
            const prefix0.MyReflectable(), null)
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(r'code', 41990, 8, const prefix0.MyReflectable(),
            -1, -1, -1, null, null, null, #code),
        r.ParameterMirrorImpl(
            r'message',
            41990,
            8,
            const prefix0.MyReflectable(),
            -1,
            -1,
            -1,
            null,
            null,
            null,
            #message),
        r.ParameterMirrorImpl(r'data', 25606, 8, const prefix0.MyReflectable(),
            -1, -1, -1, null, null, null, #data),
        r.ParameterMirrorImpl(r'json', 2129926, 9,
            const prefix0.MyReflectable(), -1, -1, -1, null, null, null, null),
        r.ParameterMirrorImpl(r'other', 32774, 10,
            const prefix0.MyReflectable(), -1, -1, -1, null, null, null, null),
        r.ParameterMirrorImpl(r'invocation', 32774, 12,
            const prefix0.MyReflectable(), -1, -1, -1, null, null, null, null),
        r.ParameterMirrorImpl(
            r'count',
            41990,
            17,
            const prefix0.MyReflectable(),
            -1,
            -1,
            -1,
            null,
            null,
            null,
            #count),
        r.ParameterMirrorImpl(r'json', 2129926, 18,
            const prefix0.MyReflectable(), -1, -1, -1, null, null, null, null)
      ],
      <Type>[prefix1.Result, prefix2.CounterDTO],
      2,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'toJson': (dynamic instance) => instance.toJson,
        r'code': (dynamic instance) => instance.code,
        r'message': (dynamic instance) => instance.message,
        r'data': (dynamic instance) => instance.data,
        r'count': (dynamic instance) => instance.count
      },
      {},
      <m.LibraryMirror>[
        r.LibraryMirrorImpl(r'', Uri.parse(r'reflectable://0/'),
            const prefix0.MyReflectable(), const <int>[], {}, {}, null, null),
        r.LibraryMirrorImpl(r'', Uri.parse(r'reflectable://1/'),
            const prefix0.MyReflectable(), const <int>[], {}, {}, null, null)
      ],
      []),
  const prefix1.MetaReflector(): r.ReflectorData(
      <m.TypeMirror>[], null, null, <Type>[], 0, {}, {}, null, []),
  const prefix2.MetaReflector(): r.ReflectorData(
      <m.TypeMirror>[], null, null, <Type>[], 0, {}, {}, null, [])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
